### ISSUE TITLE
Form does not update with new initialValues

### ISSUE THREAD

**Issue by jilliankeenan** [puppetlabs/design-system#317] opened 2020-10-01 19:01 UTC
## Describe the Bug

The form component is not updating when new initialValues are provided. This is breaking functionality where forms are expected to 'reset' after submit.

## Expected Behavior

The form should update when new initialValues are provided.

**Comment by trybick** [comment] 2020-10-01 23:23
Hi I would like to volunteer. However I'm trying to reproduce this but having trouble. Does it occur when trying to type text into the Form component on the website?

**Comment by jilliankeenan** [comment] 2020-10-02 15:25
@trybick Great thanks for picking this up! 

So if you have a look at the `<Form />` component I've wrote some example code that you can just copy and paste into our live editor. 

Once you've pasted this code you'll be able to see at the bottom of the rendered component I've added a small checkbox, this is the best way I could think of showing how to recreate this bug. 

When you click the checkbox it should be switching out the values object of `initialValues` with `newValues` and vice versa, the values of the component have changed and I should be seeing that change take place in the Form, however I'm not. 

Does this example make sense?

`const movieOptions = [
  { value: 'american-treasure', label: 'American Treasure' },
  { value: 'ghost-rider', label: 'Ghost Rider' },
  { value: 'point_break', label: 'Point Break' },
];

const initialValues = {
  controlledFirstName: 'Sponge',
  controlledLastName: 'Bob',
  controlledPassword: '',
  controlledFavoriteMovie: '',
  controlledNotARobot: false,
};

const newValues = {
  controlledFirstName: 'check',
  controlledLastName: 'Bob',
  controlledPassword: '',
  controlledFavoriteMovie: '',
  controlledNotARobot: false,
};

/** Mock api call method */
const submitForm = values => values;

class MyPage extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      values: initialValues,
      submitting: false,
    };

    this.onSubmit = this.onSubmit.bind(this);
  }

  onSubmit(values) {
    this.setState({ submitting: true });

    submitForm(values);

    this.setState({ submitting: false, values });
  }

  render() {
    const { values, submitting } = this.state;

    return (
    <div>
      <Form
        submittable
        cancellable
        initialValues={values}
        submitting={submitting}
        onSubmit={this.onSubmit}
      >
        <Form.Field
          type="text"
          name="controlledFirstName"
          autoComplete="firstname"
          label="First name"
          placeholder="Enter your first name..."
        />
        <Form.Field
          type="text"
          name="controlledLastName"
          autoComplete="lastname"
          label="Last name"
          placeholder="Enter your last name..."
        />
        <Form.Field
          type="password"
          autoComplete="current-password"
          name="controlledPassword"
          label="Password"
          placeholder="Enter your password..."
          description="Please enter your password"
          error="You goofed up now"
        />
        <Form.Field
          type="select"
          name="controlledFavoriteMovie"
          label="favorite movie"
          placeholder="Choose a movie"
          options={movieOptions}
        />
        <Form.Field
          type="checkbox"
          name="controlledNotARobot"
          label="Not a robot"
          description="Are you a human?"
        />
      </Form>
      
      <input type='checkbox' onChange={(event) => {this.setState({values : event.target.value === 'true' ? newValues: initialValues }) }}/>
      </div>
    );
  }
}

<MyPage />;`

**Comment by vine77** [comment] 2020-10-02 15:45
Thanks for investigating this @trybick and @jilliankeenan. I was actually able to verify that `initialValues` seems to be updating, so I think this bug report must be outdated or already fixed, so I'm going to close it.

```
const movieOptions = [
  { value: 'american-treasure', label: 'American Treasure' },
  { value: 'ghost-rider', label: 'Ghost Rider' },
  { value: 'point_break', label: 'Point Break' },
];

const initialValues = {
  controlledFirstName: 'unchecked',
  controlledLastName: 'initial values',
  controlledPassword: '',
  controlledFavoriteMovie: '',
  controlledNotARobot: false,
};

const newValues = {
  controlledFirstName: 'checked',
  controlledLastName: 'new values',
  controlledPassword: '',
  controlledFavoriteMovie: '',
  controlledNotARobot: false,
};

/** Mock api call method */
const submitForm = (values) => values;

class MyPage extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      values: initialValues,
      submitting: false,
    };

    this.onSubmit = this.onSubmit.bind(this);
  }

  onSubmit(values) {
    this.setState({ submitting: true });

    submitForm(values);

    this.setState({ submitting: false, values });
  }

  render() {
    const { values, submitting } = this.state;

    return (
      <div>
        <Form
          submittable
          cancellable
          initialValues={values}
          submitting={submitting}
          onSubmit={this.onSubmit}
        >
          <Form.Field
            type="text"
            name="controlledFirstName"
            autoComplete="firstname"
            label="First name"
            placeholder="Enter your first name..."
          />
          <Form.Field
            type="text"
            name="controlledLastName"
            autoComplete="lastname"
            label="Last name"
            placeholder="Enter your last name..."
          />
          <Form.Field
            type="password"
            autoComplete="current-password"
            name="controlledPassword"
            label="Password"
            placeholder="Enter your password..."
            description="Please enter your password"
            error="You goofed up now"
          />
          <Form.Field
            type="select"
            name="controlledFavoriteMovie"
            label="favorite movie"
            placeholder="Choose a movie"
            options={movieOptions}
          />
          <Form.Field
            type="checkbox"
            name="controlledNotARobot"
            label="Not a robot"
            description="Are you a human?"
          />
        </Form>

        <label>
          <input
            type="checkbox"
            onChange={(event) => {
              this.setState({
                values:
                  event.target.checked === true ? newValues : initialValues,
              });
            }}
          />
          Check this checkbox to see new form value
        </label>
      </div>
    );
  }
}

<MyPage />;
```

**Closed** 2020-10-02 15:45 UTC
Labels: bug
